### ISSUE TITLE
layer can't be loaded

### ISSUE THREAD

**Issue by EtienneParmentier** [nyorain/vil#20]
Platform:  Linux X11 and Wayland
Layer version: 1.2.162
Branch/commit: 259be83b7c24c30d7e19d23c4f7e1fc1f8e92495 (top of main)
GPU: Intel(R) UHD Graphics (JSL)

I compiled and installed V.I.L, and verified it's installation using vulkanCapsViewer command:
![Screenshot](https://github.com/user-attachments/assets/8bae0a5d-1159-4c56-ac32-fb1581c4b215)

I then tried to load it inside my application by specifying it's name, and my application code finds it and displays it's version.
But, the call to ```vkInstanceCreate``` fails, and the ```VK_ERROR_LAYER_NOT_PRESENT``` error is returned.

More info:
I am using vulkan API 1.3, this may be the cause of the issues, as the spec version of the V.I.L is 1.2.162

**Comment by nyorain** [comment]
For future reference: The spec version of vil does not matter in this case. Just make sure the VkLayer_live_introspection.json is properly installed, see the readme for more details.

**Comment by EtienneParmentier** [comment]
I fixed it by adding the .so file directory to LD_LIBRARY_PATH, it had nothing to do with V.I.L
